version: '3.9'

services:

  grafana:
    image: grafana/grafana:latest
    env_file:
      - .env
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - ${GF_PORT}:${GF_PORT}

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=pyamqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@queue:${RABBITMQ_PORT}/
      - FLOWER_PORT=5555
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}


  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}

volumes:
  grafana-data:
