version: '3.9'

services:

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      - PGPORT=${PG_PORT}
      - PGTZ=${TZ}
    ports:
      - ${PG_PORT}:${PG_PORT}

  app:
    build:
      context: backend
      dockerfile: backend.dockerfile
    command: ./start.sh
    env_file:
      - .env
    environment:
      - PG_HOST=db
      - RABBITMQ_HOST=queue
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}


  queue:
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=queue
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_HTTP_PORT}:${RABBITMQ_HTTP_PORT}

  celeryworker:
    build:
      context: backend
      dockerfile: celeryworker.dockerfile
    depends_on:
      - db
      - queue
    env_file:
      - .env
    environment:
      - PG_HOST=db
      - RABBITMQ_HOST=queue
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
