version: '3.9'

services:

  db:
    image: postgres:${PG_VERSION}
    environment:
      - POSTGRES_USER=${PG_SUPERUSER}
      - POSTGRES_PASSWORD=${PG_SUPERUSER_PASSWORD}
      - POSTGRES_DB=${PG_NAME}
      - PGPORT=${PG_PORT}
      - PGTZ=${PG_TZ}
      - TZ=${PG_TZ}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - backend

  redis:
    image: redis:latest
    command: --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
    networks:
      - backend

  app:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5435/${PG_NAME}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
