version: '3.9'

services:

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${PG_SUPERUSER}
      - POSTGRES_PASSWORD=${PG_SUPERUSER_PASSWORD}
      - POSTGRES_DB=${PG_NAME}
      - PGPORT=${PG_PORT}
      - PGTZ=${TZ}
      - TZ=${TZ}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - backend

  app:
    build: .
    restart: always
    command: /app/app/start.sh
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
      - DATABASE_URL=postgresql://${PG_SUPERUSER}:${PG_SUPERUSER_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_NAME}
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
